### ISSUE TITLE
How to use xml2csv using a xml file as input??

### ISSUE THREAD

**Issue by aborruso** [DALDEI/xmlsh1_3#3]
Hi,
I have dowloaded and uncompressed xmlsh binaries, and then run xmlsh (on Linux).

How to run xml2csv to convert an input xml file to csv??

`xml2csv ./input.xml >./output.csv` does not work. The process starts and remains active indefinitely

Thank you

**Comment by DALDEI** [comment]
xml2csv takes the xml file as standard input not argument.
Try 

`xml2csv < input.xml > output.csv`
